/** English-only overrides for automated exercise test labels (same pattern as `content/en/exercises`). */

export type ExerciseTestLabelOverrides = Partial<Record<string, string>>

export const exerciseTestOverrides: Record<string, ExerciseTestLabelOverrides> = {
  counter: {
    previewMissing: "Exercise preview",
    plusIncrements: "+ increments by one",
    liveCountNotHardcoded: "counter shows live count (not a hardcoded 0)",
    minusDecrements: "− decrements",
    resetZero: "reset sets display to 0",
    plusThree: "+3 adds three",
    detailMissingRoot: "missing #root",
  },
  "auto-focus": {
    inputFocusesOnMount: "input focuses on mount",
    focusButtonFocusesInput: "'Focus' button applies programmatic focus",
    inputIsControlled: "input text is controlled state",
    renderCounterInRef: "render counter uses a ref (does not cause re-renders)",
    clearResetsText: "'Clear' button resets text and focuses input",
  },
  stopwatch: {
    requiredElementsPresent: "required stopwatch elements are present",
    initialTimeZero: "initial time is 00:00.00",
    timeFormat: "time uses mm:ss.cc format",
    startAdvancesTime: "start advances the timer",
    pauseStopsTime: "pause stops the timer",
    resetStopsAndClears: "reset clears and pauses the timer",
  },
  "use-memo-filter": {
    requiredElementsPresent: "required filter elements are present",
    listRenders: "task list renders",
    queryFiltersList: "query filters the list",
    orderChangesSort: "sort order changes the first result",
    counterDoesNotRecalculate: "counter does not recalculate the list",
  },
  "optimistic-like": {
    requiredElementsPresent: "required like button is present",
    initialLikes: "initial likes start at 42",
    optimisticIncrementImmediate: "click increments optimistically",
    pendingVisualState: "pending state gives visual feedback",
    successCommitsLike: "successful save commits the like",
    failureRevertsOptimisticLike: "failed save reverts the optimistic value",
  },
  "todo-list": {
    requiredElementsPresent: "required todo form elements are present",
    submitAddsTrimmedItem: "submit adds a trimmed item",
    emptySubmitDoesNotAdd: "empty submit does not add an item",
    multipleItemsUseIds: "multiple items render independently",
    clickTextTogglesDone: "clicking text toggles done",
    removeDeletesOnlyOneItem: "remove deletes only one item",
  },
  "form-reducer": {
    requiredElementsPresent: "required form elements are present",
    submitDisabledWhenInvalid: "submit starts disabled while invalid",
    blurShowsFieldError: "blur shows the field error",
    submitShowsAllErrors: "submit reveals all relevant errors",
    validValuesEnableSubmit: "valid values enable submit",
    successfulSubmitShowsSent: "successful submit shows sent state",
  },
  "fetch-user": {
    requiredElementsPresent: "required user buttons are present",
    fetchRunsWithSignal: "fetch runs with an AbortController signal",
    loadingStateShown: "loading state is shown",
    buttonsChangeUserImmediately: "user buttons update immediately",
    staleRequestsAbort: "stale requests are aborted",
    staleResponseIgnored: "stale responses do not overwrite the UI",
    latestDataShown: "latest response is shown",
    abortErrorIgnored: "AbortError is ignored",
  },
  "theme-context": {
    requiredElementsPresent: "required theme controls are present",
    initialThemeDark: "initial theme is dark",
    themeToggleChangesCard: "theme toggle updates the card",
    tickChangesOnlyParentState: "tick changes parent state",
    toolbarDoesNotRerenderOnTick: "Toolbar does not re-render on tick",
  },
  "use-callback": {
    requiredElementsPresent: "required list controls are present",
    initialItemsRender: "initial items render",
    counterIncrements: "counter increments",
    itemsDoNotRerenderOnCounter: "items do not re-render on counter changes",
    deleteRemovesOneItem: "delete removes one item",
  },
  "transition-tabs": {
    requiredElementsPresent: "required tab buttons are present",
    initialTabRenders: "initial tab renders",
    slowTabRendersList: "slow tab renders the list",
    tabsSwitchContent: "tabs switch content",
    pendingVisualFeedback: "pending transition has visual feedback",
  },
  "action-form": {
    requiredElementsPresent: "required action form elements are present",
    invalidUsernameShowsError: "invalid username shows an error",
    invalidEmailShowsError: "invalid email shows an error",
    pendingDisablesControls: "pending submit disables controls",
    validSubmitShowsWelcome: "valid submit shows welcome state",
  },
  "debounced-search": {
    requiredElementsPresent: "required search elements are present",
    initialListRenders: "initial list renders",
    inputUpdatesImmediately: "input updates immediately",
    deferredListEventuallyUpdates: "deferred list eventually updates",
    staleFeedbackAvailable: "stale state provides visual feedback",
  },
  "lazy-modal": {
    requiredElementsPresent: "required modal trigger is present",
    modalInitiallyAbsent: "modal is absent initially",
    firstOpenShowsFallback: "first open shows loading fallback",
    modalAppearsAfterDelay: "modal appears after lazy delay",
    closeHidesModal: "close hides the modal",
    reopenUsesCachedModule: "reopen uses the cached module",
  },
}
